name: ci
on:
  push:
    paths-ignore:
      - "README.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "README.md"
      - "LICENSE"
concurrency:
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true
jobs:
  build-ziggy:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        opt: [Debug, ReleaseSafe]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Zig
        uses: mlugg/setup-zig@v2
      - name: Build
        working-directory: ./ziggy
        run: zig build -Doptimize=${{ matrix.opt }}
  build-ubuntu:
    strategy:
      fail-fast: false
      matrix:
        skip-build: [client, server]
        tracy-flag: [true, false]
        opt: [Debug, ReleaseSafe]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install libglfw3 libglfw3-dev libatk1.0-0 libgtk-3-dev libglib2.0-dev
      - name: Install Zig
        uses: mlugg/setup-zig@v2
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true
      - name: Build
        run: zig build -D${{ matrix.skip-build }}=false -Dtracy=${{ matrix.tracy-flag }} -Doptimize=${{ matrix.opt }}
  build-windows:
    strategy:
      fail-fast: false
      matrix:
        skip-build: [client, server]
        tracy-flag: [true, false]
        opt: [Debug, ReleaseSafe]
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Zig
        uses: mlugg/setup-zig@v2
      - name: Install Vulkan SDK
        uses: humbletim/install-vulkan-sdk@v1.2
        with:
          version: 1.4.309.0
          cache: true
      - name: Build
        run: zig build -D${{ matrix.skip-build }}=false -Dtracy=${{ matrix.tracy-flag }} -Doptimize=${{ matrix.opt }}